#!/bin/sh

if [ -e "/etc/config/ucitrack" ]; then
    uci -q batch <<-EOF
		delete ucitrack.@nodepool_server[-1]
		add ucitrack nodepool_server
		set ucitrack.@nodepool_server[-1].init=nodepool_server
		commit ucitrack
EOF
fi

uci -q batch <<-EOF
	delete firewall.nodepool_server
	set firewall.nodepool_server=include
	set firewall.nodepool_server.type='script'
	set firewall.nodepool_server.path='/var/etc/nodepool_server.include'
EOF

if [ -x "/sbin/fw3" ]; then
	uci -q set firewall.nodepool_server.reload='1'
else
	uci -q delete firewall.nodepool_server.reload
	uci -q delete firewall.nodepool_server.fw4_compatible
fi
uci commit firewall

# Migrate server sections from the old `user` section type. New user entries
# also use `user`, so only sections with a server `type` option are renamed.
for sid in $(uci -q show nodepool_server | sed -n 's/^nodepool_server\.\([^.=]*\)=user$/\1/p'); do
	if [ -n "$(uci -q get "nodepool_server.${sid}.type")" ]; then
		uci -q set "nodepool_server.${sid}=server"
	fi
done
for sid in $(uci -q show nodepool_server | sed -n 's/^nodepool_server\.\([^.=]*\)\.protocol=dokodemo-door$/\1/p'); do
	uci -q set "nodepool_server.${sid}.protocol=tunnel"
done

uci -q commit nodepool_server

rm -f /tmp/luci-indexcache /tmp/luci-indexcache.*
rm -rf /tmp/luci-modulecache/
killall -HUP rpcd 2>/dev/null

exit 0
