log:
  level: info
  file: "/var/log/mosdns.log"

# API 鍏ュ彛璁剧疆
api:
  http: "0.0.0.0:9091"

include: []

plugins:
  # 鍥藉唴鍩熷悕
  - tag: geosite_cn
    type: domain_set
    args:
      files:
        - "/var/mosdns/geosite_cn.txt"

  # 鍥藉唴 IP
  - tag: geoip_cn
    type: ip_set
    args:
      files:
        - "/var/mosdns/geoip_cn.txt"

  # 鍥藉鍩熷悕
  - tag: geosite_no_cn
    type: domain_set
    args:
      files:
        - "/var/mosdns/geosite_geolocation-!cn.txt"

  # 缂撳瓨
  - tag: lazy_cache
    type: cache
    args:
      size: 20000
      lazy_cache_ttl: 86400
      dump_file: "/etc/mosdns/cache.dump"
      dump_interval: 600

  # 杞彂鑷虫湰鍦版湇鍔″櫒
  - tag: forward_local
    type: forward
    args:
      upstreams:
        - addr: "https://doh.pub/dns-query"
          bootstrap: 180.76.76.76
        - addr: 119.29.29.29

  # 杞彂鑷宠繙绋嬫湇鍔″櫒
  - tag: forward_remote
    type: forward
    args:
      upstreams:
        - addr: tls://8.8.8.8
          enable_pipeline: false

  # 鍥藉唴瑙ｆ瀽
  - tag: local_sequence
    type: sequence
    args:
      - exec: $forward_local

  # 鍥藉瑙ｆ瀽
  - tag: remote_sequence
    type: sequence
    args:
      - exec: prefer_ipv4
      - exec: $forward_remote

  # 鏈夊搷搴旂粓姝㈣繑鍥?  - tag: has_resp_sequence
    type: sequence
    args:
      - matches: has_resp
        exec: accept

  # fallback 鐢ㄦ湰鍦版湇鍔″櫒 sequence
  # 杩斿洖闈炲浗鍐?ip 鍒?drop_resp
  - tag: query_is_local_ip
    type: sequence
    args:
      - exec: $local_sequence
      - matches: "!resp_ip $geoip_cn"
        exec: drop_resp

  # fallback 鐢ㄨ繙绋嬫湇鍔″櫒 sequence
  - tag: query_is_remote
    type: sequence
    args:
      - exec: $remote_sequence

  # fallback 鐢ㄨ繙绋嬫湇鍔″櫒 sequence
  - tag: fallback
    type: fallback
    args:
      primary: query_is_local_ip
      secondary: query_is_remote
      threshold: 500
      always_standby: true

  # 鏌ヨ鍥藉唴鍩熷悕
  - tag: query_is_local_domain
    type: sequence
    args:
      - matches: qname $geosite_cn
        exec: $local_sequence

  # 鏌ヨ鍥藉鍩熷悕
  - tag: query_is_no_local_domain
    type: sequence
    args:
      - matches: qname $geosite_no_cn
        exec: $remote_sequence

  # 涓昏鐨勮繍琛岄€昏緫鎻掍欢
  # sequence 鎻掍欢涓皟鐢ㄧ殑鎻掍欢 tag 蹇呴』鍦?sequence 鍓嶅畾涔夛紝
  # 鍚﹀垯 sequence 鎵句笉鍒板搴旀彃浠躲€?  - tag: main_sequence
    type: sequence
    args:
      - exec: $lazy_cache
      - exec: jump has_resp_sequence
      - exec: $query_is_local_domain
      - exec: jump has_resp_sequence
      - exec: $query_is_no_local_domain
      - exec: jump has_resp_sequence
      - exec: $fallback

  # 鍚姩 udp 鏈嶅姟鍣ㄣ€?  - tag: udp_server
    type: udp_server
    args:
      entry: main_sequence
      listen: ":5335"

  # 鍚姩 tcp 鏈嶅姟鍣ㄣ€?  - tag: tcp_server
    type: tcp_server
    args:
      entry: main_sequence
      listen: ":5335"
