#!/bin/sh

if [ -e "/etc/config/ucitrack" ]; then
    uci -q batch <<-EOF
 		delete ucitrack.@nodehub[-1]
		add ucitrack nodehub
		set ucitrack.@nodehub[-1].init=nodehub
		commit ucitrack
EOF
fi

uci -q batch <<-EOF
	delete firewall.nodehub
	set firewall.nodehub=include
	set firewall.nodehub.type='script'
	set firewall.nodehub.path='/var/etc/nodehub.include'

	set dhcp.@dnsmasq[0].localuse=1
	commit dhcp
	set uhttpd.main.max_requests=50
	commit uhttpd
EOF

if [ -x "/sbin/fw3" ]; then
	uci -q set firewall.nodehub.reload='1'
else
	uci -q delete firewall.nodehub.reload
	uci -q delete firewall.nodehub.fw4_compatible
fi
uci commit firewall

[ ! -s "/etc/config/nodehub" ] && cp -f /usr/share/nodehub/0_default_config /etc/config/nodehub

chmod +x /usr/share/nodehub/*.sh

[ "$(uci -q get nodehub.@global_xray[0].sniffing)" == "1" ] && [ "$(uci -q get nodehub.@global_xray[0].route_only)" != "1" ] && uci -q set nodehub.@global_xray[0].sniffing_override_dest=1
uci -q delete nodehub.@global_xray[0].sniffing
uci -q delete nodehub.@global_xray[0].route_only

[ "$(uci -q get nodehub.@global_haproxy[0].health_check_type)" = "nodehub_logic" ] && uci -q set nodehub.@global_haproxy[0].health_check_type='script_logic'

for sid in $(uci show nodehub | grep "=socks" | awk -F '.' '{print $2}' | awk -F '=' '{print $1}'); do
	if [ -z "$(echo ${sid} | grep '^socks_')" ]; then
		new_id="socks_$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 5)"
		old_ref="Socks_${sid}"
		uci -q rename nodehub.${sid}="${new_id}"
		for item in $(uci show nodehub | grep "='${old_ref}'\$" | cut -d '=' -sf 1); do
			uci -q set ${item}="${new_id}"
		done
		unset sid new_id old_ref item
	fi
done
for sid in $(uci show nodehub | grep "@acl_rule" | cut -d '.' -sf 2 | cut -d '=' -sf 1); do
	new_id="acl_$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 5)"
	uci -q rename nodehub.${sid}="${new_id}"
	unset sid new_id
done
for sid in $(uci show nodehub | grep "@subscribe_list" | cut -d '.' -sf 2 | cut -d '=' -sf 1); do
	new_id="sub_$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 5)"
	uci -q rename nodehub.${sid}="${new_id}"
	unset sid new_id
done

uci -q commit nodehub

sed -i "s#add_from#group#g" /etc/config/nodehub 2>/dev/null

rm -f /tmp/luci-indexcache /tmp/luci-indexcache.*
rm -rf /tmp/luci-modulecache/
killall -HUP rpcd 2>/dev/null

exit 0
