#!/bin/sh

if [ -e "/etc/config/ucitrack" ]; then
    uci -q batch <<-EOF
		delete ucitrack.@nodehub_server[-1]
		add ucitrack nodehub_server
		set ucitrack.@nodehub_server[-1].init=nodehub_server
		commit ucitrack
EOF
fi

uci -q batch <<-EOF
	delete firewall.nodehub_server
	set firewall.nodehub_server=include
	set firewall.nodehub_server.type='script'
	set firewall.nodehub_server.path='/var/etc/nodehub_server.include'
EOF

if [ -x "/sbin/fw3" ]; then
	uci -q set firewall.nodehub_server.reload='1'
else
	uci -q delete firewall.nodehub_server.reload
	uci -q delete firewall.nodehub_server.fw4_compatible
fi
uci commit firewall

# Migrate server sections from the old `user` section type. New user entries
# also use `user`, so only sections with a server `type` option are renamed.
for sid in $(uci -q show nodehub_server | sed -n 's/^nodehub_server\.\([^.=]*\)=user$/\1/p'); do
	if [ -n "$(uci -q get "nodehub_server.${sid}.type")" ]; then
		uci -q set "nodehub_server.${sid}=server"
	fi
done
for sid in $(uci -q show nodehub_server | sed -n 's/^nodehub_server\.\([^.=]*\)\.protocol=dokodemo-door$/\1/p'); do
	uci -q set "nodehub_server.${sid}.protocol=tunnel"
done

uci -q commit nodehub_server

rm -f /tmp/luci-indexcache /tmp/luci-indexcache.*
rm -rf /tmp/luci-modulecache/
killall -HUP rpcd 2>/dev/null

exit 0
