#!/bin/sh
uci batch <<-EOF
	set network.lan.gateway='192.168.2.2'
	set network.lan.dns='223.5.5.5'
	commit network
	set dhcp.@dnsmasq[0].server='223.5.5.5'
	set dhcp.lan.ignore=1
	set dhcp.lan.dhcpv6='disabled'
	commit dhcp
EOF
exit 0
