#!/bin/sh
uci batch <<-EOF
	set network.lan.gateway='192.168.2.2'
	set network.lan.dns='223.5.5.5'
	delete network.lan.ip6assign
	set network.wan=interface
	set network.wan.proto=none
	set network.wan.disabled=1
	set network.wan6=interface
	set network.wan6.proto=none
	set network.wan6.disabled=1
	delete network.globals.ula_prefix
	commit network
	set dhcp.@dnsmasq[0].server='223.5.5.5'
	set dhcp.@dnsmasq[0].filter_aaaa=1
	set dhcp.@dnsmasq[0].filter_a=1
	commit dhcp
	set firewall.@zone[1].ipv6=0
	commit firewall
EOF
sysctl -w net.ipv6.conf.all.disable_ipv6=1
sysctl -w net.ipv6.conf.default.disable_ipv6=1
echo "net.ipv6.conf.all.disable_ipv6=1" > /etc/sysctl.d/99-disable-ipv6.conf
echo "net.ipv6.conf.default.disable_ipv6=1" >> /etc/sysctl.d/99-disable-ipv6.conf
exit 0
